name: Artillery Testing

on:
  push:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          npm ci
          npm install -g artillery

      - name: Run Artillery load test
        run: artillery run artillery-test.yml

      - name: Upload Artillery report artifact
        uses: actions/upload-artifact@v2
        with:
          name: artillery-report
          path: reports
  